name: Build yesterday's JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install yfinance pandas

      - name: Ensure tickers.txt (create if <400)
        run: |
          set -euo pipefail
          n=$(grep -E "^[A-Z]" tickers.txt 2>/dev/null | wc -l || true)
          if [ "$n" -lt 400 ]; then
            echo "tickers.txt missing or too short; writing static S&P500 list"
            cat > tickers.txt <<'EOF'
AAPL
MSFT
GOOGL
AMZN
META
TSLA
BRK.B
JPM
JNJ
V
PG
NVDA
HD
MA
UNH
XOM
BAC
VZ
ADBE
PFE
KO
NFLX
DIS
PEP
CSCO
INTC
ABT
CRM
CMCSA
T
WMT
MRK
CVX
NKE
ORCL
MCD
COST
ACN
DHR
LLY
WFC
MDT
TXN
UPS
TMO
NEE
HON
UNP
AMGN
LOW
MS
GS
LIN
QCOM
BMY
SCHW
RTX
INTU
COP
AMT
PM
C
AXP
CAT
BLK
IBM
SPGI
CVS
DE
GE
MMM
NOW
BKNG
ADI
ISRG
GILD
SYK
ZTS
PLD
ETN
MDLZ
TJX
PGR
FIS
FISV
USB
PNC
CB
MMC
MO
CI
DUK
TGT
SO
CL
BDX
APD
NSC
ADP
SHW
EL
REGN
EQIX
ECL
ICE
CME
HUM
PSA
WM
ITW
FDX
SRE
NOC
GD
TRV
AON
...
# (keep adding until you have >400 symbols)
EOF
          else
            echo "tickers.txt has $n symbols"
          fi

      - name: Build JSON (allow retry)
        run: |
          set -e
          python fetch_ohlc.py || true

      - name: Sanity check
        run: |
          python - <<'PY'
          import json, pathlib
          rows = len(json.loads(pathlib.Path("data/yesterday.json").read_text()))
          print(f"rows={rows}")
          assert rows >= 400, f"Upstream incomplete: rows={rows}"
          PY

      - name: Commit & push
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.csv data/yesterday.json tickers.txt
          git commit -m "update aggregates and yesterday.json" || echo "nothing to commit"
          git push
