name: Build yesterday's JSON

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip && ( [ -f requirements.txt ] && pip install -r requirements.txt || true ) && pip install pandas lxml yfinance

      # Create/refresh tickers.txt from Wikipedia if it has < 400 symbols
      - name: Ensure tickers.txt
        shell: bash
        run: |
          set -e
          n=0; [ -f tickers.txt ] && n=$(grep -E '^[A-Za-z0-9.-]+' tickers.txt | wc -l || true)
          echo "Existing tickers count: $n"
          if [ "$n" -lt 400 ]; then
            python -c "import pandas as pd, pathlib; url='https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'; df=pd.read_html(url, flavor='lxml')[0]; syms=(df['Symbol'].astype(str).str.replace('.','-', regex=False).str.upper().tolist()); syms=sorted(dict.fromkeys(syms)); pathlib.Path('tickers.txt').write_text('\n'.join(syms)+'\n', encoding='utf-8'); print(f'WROTE {len(syms)} symbols to tickers.txt')"
          fi

      - name: Guard >= 400 tickers
        run: |
          n=$(grep -E '^[A-Za-z0-9.-]+' tickers.txt | wc -l)
          echo "tickers.txt count: $n"
          if [ "$n" -lt 400 ]; then
            echo "::error::tickers.txt has only $n symbols"
            exit 1
          fi

      - name: Build data (try 1)
        run: python fetch_ohlc.py

      - name: Sanity (try 1)
        id: sanity1
        run: python -c "import json, pathlib, sys; p=pathlib.Path('data/yesterday.json'); data=json.loads(p.read_text()) if p.exists() else []; rows=len(data) if isinstance(data,list) else 0; print('rows=',rows); sys.exit(0 if rows>=400 else 1)"

      - name: Retry build (try 2)
        if: failure()
        run: bash -lc "echo 'retrying after 90s…'; sleep 90; python fetch_ohlc.py"

      - name: Sanity (try 2)
        if: always()
        run: python -c "import json, pathlib, sys; p=pathlib.Path('data/yesterday.json'); data=json.loads(p.read_text()) if p.exists() else []; rows=len(data) if isinstance(data,list) else 0; print('rows=',rows); sys.exit(0 if rows>=400 else 1)"

      - name: Commit & push outputs (only if complete)
        if: success()
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json data/*.csv tickers.txt 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "build: update aggregates and yesterday.json"
            git pull --rebase origin main || true
            git push origin HEAD:main
          fi
