name: Build & Publish OHLC

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 22 * * 1-5'  # weekdays 22:15 UTC

permissions:
  contents: write

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Debug: show what's in the workspace so we can confirm paths ---
      - name: Inspect workspace (debug)
        run: |
          echo "pwd:" && pwd
          echo "root listing:" && ls -la
          echo "scripts listing:" && ls -la scripts || true
          echo "tracked files:" && git ls-files | sort

      # --- Run your build scripts (prefer scripts/; fall back to root) ---
      - name: Fetch OHLC
        run: |
          set -euo pipefail
          if [ -f scripts/fetch_ohlc.py ]; then
            python scripts/fetch_ohlc.py
          elif [ -f fetch_ohlc.py ]; then
            python fetch_ohlc.py
          else
            echo "fetch_ohlc.py not found in scripts/ or repo root."
            exit 1
          fi

      - name: Update tickers metadata
        run: |
          set -euo pipefail
          if [ -f scripts/update_tickers.py ]; then
            python scripts/update_tickers.py
          elif [ -f update_tickers.py ]; then
            python update_tickers.py
          else
            echo "update_tickers.py not found in scripts/ or repo root."
            exit 1
          fi

      - name: Upload R2 tickers (optional)
        if: always()
        run: |
          set -euo pipefail
          if [ -f scripts/upload_r2_tickers.py ]; then
            python scripts/upload_r2_tickers.py
          elif [ -f upload_r2_tickers.py ]; then
            python upload_r2_tickers.py
          else
            echo "upload_r2_tickers.py not found in scripts/ or repo root."
            exit 1
          fi

      # --- Commit any changed files back to main (only if there are changes) ---
      - name: Commit & push changes
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "CI: update OHLC $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
