name: Build yesterday's JSON

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # keep it minimal but ensure read_html works
          pip install pandas lxml
          # if you have a requirements.txt, this won't hurt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Build/refresh tickers.txt WITHOUT yfinance.
      # Source: Wikipedia “List of S&P 500 companies”.
      - name: Ensure tickers.txt (create/fix if < 400)
        run: |
          python - <<'PY'
          import pathlib
          import pandas as pd

          p = pathlib.Path("tickers.txt")
          existing = []
          if p.exists():
              existing = [l.strip().upper() for l in p.read_text().splitlines()
                          if l.strip() and not l.strip().startswith("#")]

          if len(existing) < 400:
              url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
              # read_html needs lxml (installed above)
              df = pd.read_html(url, flavor="lxml")[0]
              tickers = (
                  df["Symbol"]
                  .astype(str)
                  .str.replace(".", "-", regex=False)   # BRK.B -> BRK-B
                  .str.upper()
                  .tolist()
              )
              p.write_text("\n".join(tickers) + "\n", encoding="utf-8")
              print(f"WROTE {len(tickers)} tickers to tickers.txt")
          else:
              print(f"FOUND {len(existing)} tickers in tickers.txt")
          PY

      - name: Guard >= 400 tickers
        run: |
          n=$(grep -v '^\s*#' tickers.txt | sed '/^\s*$/d' | wc -l)
          echo "count=$n"
          if [ "$n" -lt 400 ]; then
            echo "::error::tickers.txt has only $n symbols; need >= 400"
            exit 1
          fi

      - name: Build data
        run: python fetch_ohlc.py

      - name: Commit outputs (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "build: update data"
          git pull --rebase origin main || true
          git push origin HEAD:main
