name: Build yesterday's JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5"  # 13:00 UTC on weekdays

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install yfinance pandas requests numpy

      # ------- Get S&P500 tickers from a public CSV (no scraping) -------
      - name: Refresh S&P 500 tickers (from GitHub CSV; no scraping)
        shell: bash
        run: |
          set -euo pipefail
          have=$(grep -E '^[A-Za-z0-9.-]+' -c tickers.txt 2>/dev/null || echo 0)
          if [ "${have}" -lt 400 ]; then
            echo "Fetching S&P 500 constituents CSV…"
            tmp=$(mktemp)
            # Primary source (maintained):
            URL1="https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv"
            # Mirror:
            URL2="https://cdn.jsdelivr.net/gh/datasets/s-and-p-500-companies@master/data/constituents.csv"
            if curl -fsSL "${URL1}" -o "${tmp}"; then
              echo "Downloaded from ${URL1}"
            else
              echo "Primary failed; trying mirror…"
              curl -fsSL "${URL2}" -o "${tmp}"
            fi
            # Column 1 is the ticker symbol. Remove quotes; keep non-empty.
            tail -n +2 "${tmp}" | cut -d',' -f1 | tr -d '"' | grep -E '^[A-Za-z0-9.-]+' > tickers.txt
            rm -f "${tmp}"
          fi
          count=$(grep -E '^[A-Za-z0-9.-]+' -c tickers.txt 2>/dev/null || echo 0)
          echo "tickers.txt count: ${count}"
          if [ "${count}" -lt 400 ]; then
            echo "::error::Still fewer than 400 tickers after refresh; aborting."
            exit 1
          fi

      # ---------------------- Build OHLC snapshot -----------------------
      - name: Build data (try 1)
        shell: bash
        run: |
          set -euo pipefail
          python fetch_ohlc.py

      - name: Sanity (try 1)
        shell: bash
        run: |
          python -c "import json,sys,pathlib; p=pathlib.Path('data/yesterday.json'); data=json.loads(p.read_text()) if p.exists() else []; rows=len(data) if isinstance(data,list) else 0; print('rows=',rows); sys.exit(0 if rows>0 else 1)"

      - name: Retry build (try 2)
        if: failure()
        shell: bash
        run: |
          echo 'Retrying after 90s…'
          sleep 90
          python fetch_ohlc.py

      - name: Sanity (try 2)
        if: always()
        shell: bash
        run: |
          python -c "import json,sys,pathlib; p=pathlib.Path('data/yesterday.json'); data=json.loads(p.read_text()) if p.exists() else []; rows=len(data) if isinstance(data,list) else 0; print('rows=',rows); sys.exit(0 if rows>0 else 1)"

      - name: Upload bad_tickers (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bad_tickers
          path: build/bad_tickers.txt
          if-no-files-found: ignore

      - name: Commit & push outputs (only if complete)
        if: success()
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/latest.csv
            data/yesterday.json
            tickers.txt
            build/bad_tickers.txt
          message: "build: update aggregates and yesterday.json"
          default_author: github_actions
