name: Build yesterday's JSON

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure tickers.txt (create/fix if < 400)
        run: |
          python - <<'PY'
          import pathlib
          import yfinance as yf

          p = pathlib.Path("tickers.txt")
          if p.exists():
              lines = [l.strip().upper() for l in p.read_text().splitlines()
                       if l.strip() and not l.strip().startswith("#")]
          else:
              lines = []

          if len(lines) < 400:
              tickers = [t.upper() for t in yf.tickers_sp500()]
              p.write_text("\n".join(tickers) + "\n", encoding="utf-8")
              print(f"WROTE {len(tickers)} tickers to tickers.txt")
          else:
              print(f"FOUND {len(lines)} tickers in tickers.txt")
          PY

      - name: Guard >= 400 tickers
        run: |
          n=$(grep -v '^\s*#' tickers.txt | sed '/^\s*$/d' | wc -l)
          echo "count=$n"
          if [ "$n" -lt 400 ]; then
            echo "::error::tickers.txt has only $n symbols; need >= 400"
            exit 1
          fi

      - name: Build data
        run: python fetch_ohlc.py

      - name: Commit outputs (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "build: update data"
          git pull --rebase origin main || true
          git push origin HEAD:main
