name: Build & Deploy Tickers

on:
  workflow_dispatch:
  schedule:
    # Weekdays @ 10:45 PM UTC (adjust as you like)
    - cron: "45 22 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # 👉 This step should produce:
      #    - data/yesterday.json
      #    - data/latest.csv
      # If your repo uses a different script, change the command below.
      - name: Build OHLC artifacts
        shell: bash
        run: |
          set -euo pipefail
          python update_tickers.py

      - name: Commit & push outputs
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/yesterday.json data/latest.csv || true
          git commit -m "build: update yesterday.json & latest.csv" || echo "No changes"
          git push origin HEAD:main || echo "Push skipped"

      # 🚀 Deploy the JSON the page reads, overwriting ONE canonical file on your site
      - name: Deploy tickers.json to site via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./data/yesterday.json
          remote_path: /home/<your-account>/public_html/wp-content/uploads/data/tickers.json
