name: Build S&P500 OHLC JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'  # 03:30 UTC (10:30 PM America/Chicago)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Make sure wheels resolve cleanly
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Refresh S&P 500 tickers from Wikipedia
        run: python update_tickers.py

      - name: Build yesterday's JSON
        run: python fetch_ohlc.py

      # Be tolerant if no files were produced (e.g., a transient network hiccup)
      - name: Commit & push JSON + tickers + manifest
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p docs
          # Stage whatever exists (won't error if no match)
          git add -A docs || true
          git add tickers.txt || true
          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Daily: tickers refresh + OHLC JSON + manifest"
            git push
          else
            echo "No changes to commit."
          fi
