name: Build & Publish OHLC

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 22 * * 1-5'  # weekdays 22:15 UTC

permissions:
  contents: write

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Build steps (adjust only the script names/paths if yours differ) ---
      - name: Fetch OHLC
        run: |
          set -euo pipefail
          python scripts/fetch_ohlc.py

      - name: Update tickers metadata
        run: |
          set -euo pipefail
          python scripts/update_tickers.py

      - name: Upload R2 tickers (optional)
        if: always()  # keep if you want it to run even if previous step fails
        run: |
          set -euo pipefail
          python scripts/upload_r2_tickers.py

      # --- Commit any changed files back to main (only if there are changes) ---
      - name: Commit & push changes
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "CI: update OHLC $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
