name: Build & Publish OHLC

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 22 * * 1-5'  # weekdays 22:15 UTC

permissions:
  contents: write

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify workspace
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "tickers.txt head:"
          head -n 5 tickers.txt || echo "tickers.txt missing!"

      - name: Ensure tickers.txt exists
        run: |
          if [ ! -f tickers.txt ] && [ -f scripts/tickers.txt ]; then
            cp scripts/tickers.txt .
            echo "Copied scripts/tickers.txt -> ./tickers.txt"
          fi

      - name: Fetch OHLC
        run: |
          set -euo pipefail
          python fetch_ohlc.py

      - name: Update tickers metadata
        env:
          TICKERS_PATH: ${{ github.workspace }}/tickers.txt
        run: |
          set -euo pipefail
          echo "Forcing path for tickers.txt: $TICKERS_PATH"
          python - <<'PYCODE'
import os, pathlib, update_tickers
from pathlib import Path

tickers_file = Path(os.environ["TICKERS_PATH"])
print(f"✅ Using forced tickers path: {tickers_file.resolve()}")

# Patch update_tickers.TICKERS_TXT before calling main()
if hasattr(update_tickers, "TICKERS_TXT"):
    update_tickers.TICKERS_TXT = tickers_file
else:
    update_tickers.TICKERS_TXT = tickers_file

update_tickers.main()
PYCODE

      - name: Upload R2 tickers (optional)
        if: always()
        env:
          R2_ACCOUNT_ID:        ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID:     ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET:            ${{ secrets.R2_BUCKET }}
          R2_ENDPOINT_URL:      ${{ secrets.R2_ENDPOINT_URL }}
          R2_PUBLIC_BASE:       ${{ secrets.R2_PUBLIC_BASE }}
        run: |
          set -euo pipefail
          python upload_r2_tickers.py

      - name: Commit & push changes
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "CI: update OHLC $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
