name: Build S&P500 OHLC JSON

on:
  workflow_dispatch:
    inputs:
      limit_tickers:
        description: 'Limit number of tickers (manual test)'
        required: false
        default: '10'
      skip_zip:
        description: 'Skip ZIP (force CSV) for fast feedback'
        required: false
        default: 'true'
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      LIMIT_TICKERS: ${{ github.event.inputs.limit_tickers }}
      SKIP_ZIP: ${{ github.event.inputs.skip_zip == 'true' && '1' || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Refresh S&P 500 tickers from Wikipedia
        run: python update_tickers.py

      - name: Show fetch_ohlc.py header (debug)
        run: |
          echo "==== head(fetch_ohlc.py) ===="
          sed -n '1,80p' fetch_ohlc.py

      - name: Build yesterday's JSON
        run: python fetch_ohlc.py

      - name: Commit & push JSON + tickers + manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p docs
          git add -A docs || true
          git add tickers.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "Daily: tickers refresh + OHLC JSON + manifest"
            git push
          else
            echo "No changes to commit."
          fi
