name: build

on:
  schedule:
    # Weekdays ~6:15pm Central (adjust if you like)
    - cron: "15 23 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "--- first 3 levels ---"
          find . -maxdepth 3 -type f | sort

      - name: Build yesterday's JSON
        timeout-minutes: 15
        run: |
          python fetch_ohlc.py

      - name: Upload bad tickers (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bad_tickers
          path: build/bad_tickers.txt
          if-no-files-found: ignore

      - name: Commit & push outputs
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "build: update aggregates and yesterday.json" || echo "nothing to commit"
          git push
